### PR TITLE
Updated readme.md #14

### PR DESCRIPTION
**Pull request by Amit366**
I have updated it.

### CODE REVIEW

**Comment by Amit366** [comment]
@iiitmjay I have bought the caption to center.

**Comment by IIITM-Jay** [comment]
@Amit366 Amit can you try exploring some new fonts that can be embedded into this file... as you have to change only one line.. you can try playing with these so that you an explore more and more and develop yourself too. :hugs:

**Comment by Amit366** [comment]
@IIITM-Jay sir I am not able to change the font style.

**Comment by Amit366** [comment]
@IIITM-Jay sir please check it now

**Comment by IIITM-Jay** [comment]
@Amit366  good job Amit :sparkles: :tada: 
Heartly congratulation to be a part of the Property management System :house_with_garden: and thanks for the contribution :sparkler: :1st_place_medal:

**Comment by IIITM-Jay** [comment]
@Nandini-Jha I think its ready to go now...

**Comment by IIITM-Jay** [comment]
@all-contributors please add @Amit366 for content

**Pull request merged**
